# Site settings
title: "103 Javascript: Painting with Code"
description: ""
url: https://coderdojochi.github.io/103-js
author: "CoderDojoChi <info@coderdojochi.org>"
email: info@coderdojochi.org
twitter_username: CoderDojoChi
github_username:  CoderDojoChi
facebook_username: CoderDojoChi

baseurl: /103-js

github: [metadata]

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - reveal.js/.*
  - reveal.js/*.md
  - reveal.js/*.json
  - reveal.js/demo.html
  - reveal.js/index.html
  - reveal.js/Gruntfile.js
  - reveal.js/LICENSE
  - reveal.js/test/

include:
  - reveal.js/css/*.css
  - reveal.js/js/*.js
  - reveal.js/lib/
  - reveal.js/plugins/
  - _pages

collections:
  slides:
    output: false
  animals:
    output: false

defaults:
  - scope:
      path: "/assets/images/animals/"
      type: animals
    values:
      layout: "animals"

revealTheme:
    base: white
    custom: cdc

slideNumber:
  # Slide number formatting can be configured using these variables:
  #  "h.v": horizontal . vertical slide number (default)
  #  "h/v": horizontal / vertical slide number
  #    "c": flattened slide number
  #  "c/t": flattened slide number / total slides
  format: "c/t"

  # Control which views the slide number displays on using the "showSlideNumber" value:
  #     "all": show on all views (default)
  # "speaker": only show slide numbers on speaker notes view
  #   "print": only show slide numbers when printing to PDF
  showSlideNumber: "all"


# Reveal.initialize
#
# At the end of your page you need to initialize reveal by running the following code.
# Note that all config values are optional and will default as specified below.
#
# Full list of configuration options available here:
# https://github.com/hakimel/reveal.js#configuration
reveal:

  # Display controls in the bottom right corner
  controls: false

  # Display a presentation progress bar
  progress: true

  # Set default timing per slide in seconds
  defaultTiming: 60

  # Display the page number of the current slide
  # slideNumber: false

  # Push each slide change to the browser history
  history: true

  # Enable keyboard shortcuts for navigation
  keyboard: true

  # Enable the slide overview mode
  overview: true

  # Vertical centering of slides
  center: false

  # Enables touch navigation on devices with touch input
  touch: true

  # Loop the presentation
  loop: false

  # Change the presentation direction to be RTL
  # rtl: false

  # Randomizes the order of slides each time the presentation loads
  shuffle: false

  # Turns fragments on and off globally
  fragments: true

  # Flags if the presentation is running in an embedded mode,
  # i.e. contained within a limited portion of the screen
  # embedded: false

  # Flags if we should show a help overlay when the questionmark
  # key is pressed
  # help: true

  # Flags if speaker notes should be visible to all viewers
  # showNotes: false

  # Global override for autolaying embedded media (video/audio/iframe)
  # - null: Media will only autoplay if data-autoplay is present
  # - true: All media will autoplay, regardless of individual setting
  # - false: No media will autoplay, regardless of individual setting
  # autoPlayMedia: null

  # Number of milliseconds between automatically proceeding to the
  # next slide, disabled when set to 0, this value can be overwritten
  # by using a data-autoslide attribute on your slides
  # autoSlide: 15000

  # Stop auto-sliding after user input
  # autoSlideStoppable: false

  # Use this method for navigation when auto-sliding
  # autoSlideMethod: Reveal.navigateNext

  # Enable slide navigation via mouse wheel
  # mouseWheel: false

  # Hides the address bar on mobile devices
  # hideAddressBar: true

  # Opens links in an iframe preview overlay
  # previewLinks: false

  # Transition style
  # none/fade/slide/convex/concave/zoom
  transition: none

  # Transition speed
  # default/fast/slow
  # transitionSpeed: default

  # Transition style for full page slide backgrounds
  # none/fade/slide/convex/concave/zoom
  backgroundTransition: none

  # Number of slides away from the current that are visible
  # viewDistance: 3

  # Parallax background image
  # e.g. ""https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg""
  # parallaxBackgroundImage: ""

  # Parallax background size
  # CSS syntax, e.g. "2100px 900px"
  # parallaxBackgroundSize: ""

  # Number of pixels to move the parallax background per slide
  # - Calculated automatically unless specified
  # - Set to 0 to disable movement along an axis
  # parallaxBackgroundHorizontal: null
  # parallaxBackgroundVertical: null

  # The display mode that will be used to show slides
  # display: "block"

  # The "normal" size of the presentation, aspect ratio will be preserved
  # when the presentation is scaled to fit different resolutions. Can be
  # specified using percentage units.
  # width: 1200
  # height: 960

  # Factor of the display size that should remain empty around the content
  # margin: 0.1

  # Bounds for smallest/largest possible scale to apply to content
  # minScale: 0.2
  # maxScale: 1.5
